### ISSUE TITLE
On POP!OS Start on login and Try Icon not working

### ISSUE THREAD

**Issue by xenicle** [bithatch/snake#10]
On my POP!OS (who use Gnome 3) Start on login seem to not work and Try Icon isn't visible.

**Comment by brett-smith** [comment]
Thanks for your bug report. I just got Pop installed to confirm this, and it seems Pop is affected by this bug - https://github.com/dorkbox/SystemTray/issues/125 - in the library I use for the system tray. 

You can confirm this by trying to start Snake from the command line.  ..

```
cd /path/to/snake
GDMSESSION=ubuntu bin/snake
```

If that works, then you can make this permanent ...

```
cd /path/to/snake
echo 'setenv GDMSESSION=ubuntu' > app.cfg.d/pop-hack.cfg
```

The bug has been fixed upstream, we are just waiting for the maintainer to release a new build.

**Comment by xenicle** [comment]
Thanks for your response ans sorry for late response !

I've tried : 
 `cd /path/to/snake
GDMSESSION=ubuntu bin/snake`

And tray have not appearing, I will wait for
 Update.

**Comment by xenicle** [comment]
I have restarted my pc and make :
`export GDMSESSION=ubuntu
bin/snake`
and the tray showing !

**Comment by brett-smith** [comment]
This should be fixed now. The latest Snake release has the new DorkBox library.
