### ISSUE TITLE
Lighting Issue

### ISSUE THREAD

**Issue by TrekTheEarth** [bithatch/snake#3]
After a bit of poking I found that when the lighting profile 'wave' has it's setting set to go forward, the lights don't come on at all (for wave) when bouncing from profile to profile. When wave's setting is set to backward, jumping between say ripple > spectrum > wave , the lights work just fine.

**Comment by brett-smith** [comment]
I can confirm there are problems here, switching between effects. This is a regression that appeared when the custom effects editor was added.

**Comment by brett-smith** [comment]
Fixed in SNAPSHOT-145.
