### ISSUE TITLE
Buttons have no icons

### ISSUE THREAD

**Issue by momper14** [bithatch/snake#6]
Im Running POP!OS 20.10 with KDE and all Buttons are just blank rectangles. Any idea?

![Screenshot_snake](https://user-images.githubusercontent.com/33731661/103437694-cd33e600-4c2a-11eb-8502-9097d5ee4a23.png)

OS:
```sh
lsb_release -a
No LSB modules are available.
Distributor ID: Pop
Description:    Pop!_OS 20.10
Release:        20.10
Codename:       groovy
```

**Comment by brett-smith** [comment]
Odd. That looks like it is having a problem with FontAwesome icons. The font is included with Snake itself, and it should be using that, but to help get  to the bottom of this could you check if you have the font awesome font installed as a system or local font?

Something like ..

```
find ~/.local/share/fonts -iname '*font*awesome*'
```

and 

```
find /usr/share/fonts -iname '*font*awesome*'
```

If that comes back with some results, you could try removing those temporarily to see if it makes any difference.

**Comment by Momper14** [comment]
Tested it and you are right. Package fonts-font-awesome removed and its fine now. TY :)

**Comment by brett-smith** [comment]
Thanks for checking. 

It seems getting a long term fix for this issue so having a system fontawesome installed wont matter, is a little more complicated than I had first thought. I figured just renaming the font distributed with Snake might work, but it is more than that. 

The system font appears to be being always used for the unicode range that font awesome uses, and there is no obvious way to override this in JavaFX. A fix is likely going to mean a rethink of how Snake does icons.

**Comment by brett-smith** [comment]
Icons reworked to use https://kordamp.org/ikonli. Fixed in SNAPSHOT-145
