### ISSUE TITLE
Can't Uninstall

### ISSUE THREAD

**Issue by linnos** [bithatch/snake#7]
How do you uninstall this?

**Comment by brett-smith** [comment]
There is currently no uninstaller, but the following should work in the meantime from a terminal.

```bash
rm -fr ~/path/to/where/you/installed/snake
rm ~/.local/share/applications/snake-razer.desktop
rm ~/.local/share/pixmaps/snake-razer.png
rm ~/.config/autostart/snake-razer.desktop
```

and if you want to clear all Snake preferences, profiles etc ..

```bash
rm -fr ~/.java/.userPrefs/uk/co/bithatch/snake
```

**Comment by brett-smith** [comment]
Added page to Wiki. https://github.com/bithatch/snake/wiki/Uninstalling
