### ISSUE TITLE
How do you uninstall?

### ISSUE THREAD

**Issue by nem25** [bithatch/snake#9]
After installing snake, my computer keeps crashing every time I try to run the software. I am running it on Ubuntu 20.04.
How can I remove all the packages?

**Comment by brett-smith** [comment]
Sorry you are having troubles. Are you able to provide any screenshots or output that might help me find the problem?

There is currently no uninstaller, but you can follow the instructions here - https://github.com/bithatch/snake/wiki/Uninstalling - to do so manually.

**Comment by nem25** [comment]
Hey!

Thanks for the quick response. Happy to help as I understand you are still developing this software.
I don't have a screenshot as now it seems to behave differently every time I start it.
The first time I ran it, all the open windows on my computer turned white and the background black. I think this could have been some kind of display driver crash.
Then I restarted my computer and it opened snake but it was just a black window with the logo on top and the min/max icons, essentially the toolbar and nothing else.
The third time after restarting, it got stuck on the checking for updates window. And after that it recognised my mouse.

If there are any log files that would be handy for you to troubleshoot, do let me know where to find them.

Hope this helps!

**Comment by brett-smith** [comment]
Thanks for the info.

Those are strange symptoms indeed.  I have just published the latest snapshot, which contains some fixes for icons that *might* be related to one of the issues you are seeing, but I don't think it explains everything.

So yes, some log output might help us here. You can launch snake and log the output by running it from the command line with the following options.

```
cd /path/to/snake
bin/snake -l /tmp/snake.log
```

This will create a log file at `/tmp/snake.log`.

**Comment by nem25** [comment]
Tried the log commands but no log was created. Although this time I got a new error on starting snake. I got a screenshot this time. It was stuck on this screen; never went past it. I think that's why the log file wasn't getting created either. The dots kept spinning.
![Screenshot from 2021-02-08 12-24-35](https://user-images.githubusercontent.com/7405977/107185875-3c121500-6a09-11eb-8190-ed8068789c22.png)

**Comment by brett-smith** [comment]
Apologies, this is why I should not do releases after midnight! I had baked in a testing URL for the update server into that build. 

To correct this, launch with ..

```
bin/snake --remote-manifest http://www.bithatch.co.uk/repositories/snake/snapshot/manifest.xml
```

.. and it should fix itself. Alternatively, just download the installer again from here -https://github.com/bithatch/snake/releases/tag/v1.0-SNAPSHOT-148.
